apiVersion: apps/v1
kind: Deployment
metadata:
  name: covidtracker-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: covidtracker-app
  template:
    metadata:
      labels:
        app: covidtracker-app
    spec:
      containers:
        - name: covidtracker-container
          image: bayanaltaleb/group-project:3.0
          ports:
            - containerPort: 3000
